package com.gayedesign.alagiesaine.ebougaye;

import android.content.Intent;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.ListFragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ListAdapter;
import android.widget.ListView;

public class Religion extends ListFragment{
    ListView listView;
    int curPosition = 0;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        //View view = inflater.inflate(R.layout.fragment_article,container,false);

        ListAdapter adapter = new ArrayAdapter<String>(getActivity(),android.R.layout.simple_list_item_1,RELIGION);
        setListAdapter(adapter);

        return super.onCreateView(inflater, container, savedInstanceState);
    }

    @Override
    public void onListItemClick(ListView l, View v, int position, long id) {
        showDetails(position);
        //super.onListItemClick(l, v, position, id);
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (savedInstanceState != null){
            curPosition = savedInstanceState.getInt("savedCurPosition");
        }
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putInt("savedCurPosition",0);
    }

    private void showDetails(int position) {
        curPosition = position;
        Intent intent = new Intent(getActivity(),ReligionActivity.class);
        intent.putExtra("position",position);
        startActivity(intent);
    }

    static String[] RELIGION = {"Executions in The Gambia","Intolerance: A Catalyst for Catastrophe","Imam or Image-maker?",
            "Position of Responsibility"};

    static final String[] RELIGION_DETAILS = {
            "<font color=\"black\"><b>Executions in The Gambia: What a Rash, Irrational Act!</b><br>" +
                    "<br>" +
                    "First and foremost, I would like to state categorically- and maybe to the surprise of some readers- that I am not averse to executing people who have been proven beyond all reasonable doubt guilty of intentionally killing a fellow human being. However, I note in haste that I have a very big quarrel with the Gambian leader, Yahya Jammeh and his defenders regarding the recent executions of death row inmates in The Gambia. <br>" +
                    "<br>" +
                    "Timing <br>" +
                    "That Jammeh chose to announce his intention to carry out the executions in the presence of Muslim elders who paid him a visit during the feast marking the end of the Holy month of Ramadan- a period of exchanging visits and forgiving- is hypocritical and unwise of him. It is interpreted as lack of respect for the Islamic religion by observers who qualify it as a sacrilegious, provocative deed. To them, this act is not expected of a man of Jammeh’s ilk who portrays himself as the most pious Muslim who has ever lived on the surface of planet earth.<br>" +
                    "<br>" +
                    "The executions coincided with the rumour that a Senegalese soothsayer had predicted the downfall of Jammeh. Although the fortune-teller has denied having ever met Jammeh and predicting an abrupt end to his reign, she has confirmed meeting a delegation consisting of Jammeh’s wife and brother, and speaking to Jammeh’s mother on the phone, all of whom sought her blessings on behalf of Jammeh.  According to reports, Jammeh’s family members- notably his wife and two kids- were sent to the USA prior to the executions and are currently residing there. Judging by these facts, one can say that there might be an ulterior motive behind the executions. Many people are of the conviction that the executions have been carried out for ritual purposes (human sacrifice) or meant to serve as a deterrent to would-be coup plotters.<br>" +
                    "<br>" +
                    "Jammeh’s Dogged-determination<br>" +
                    "People were astounded by the fact that Jammeh was too adamant to execute the inmates to the extent of swearing by the name of Allah the Almighty to carry out his threat and telling people not to bother to seek clemency from him on their behalf despite the fact that he previously allowed the assassinators of a state minister and a harmless journalist to go scot-free and indemnified the murderers of armless school children who were brutally gunned down for merely demonstrating over the killing and rape of their colleague by the Gambian security forces. Jammeh’s convoy frequently kills people. Again, such killings are seen by many as a deliberate act serving the purpose of human sacrifice for the simple reason that Jammeh throws biscuits on the road for children to pick knowing very well that they can be crushed by speeding vehicles following his car. The editors of the Gambian newspaper Foroyaa have condemned the act and written to Jammeh giving him advice on the issue on several occasions but he continues turning deaf ears and blind eyes as though nothing serious has ever happened. A person who plays with human life in such a manner is not morally justified in executing people. Condoning the crime of assassination or murder in some cases or licensing some people to kill while executing others for allegedly killing people is selective justice.<br>" +
                    "<br>" +
                    "Many people wonder what Jammeh expects to gain by defying the international community and human rights organizations that appealed to him to spare the inmates immediately after he threatened to execute them, if not to scare his people through the execution as a means of clinging onto power. I am not the least convinced that his refusal to pay heed to their numerous appeals and outcry was in good faith. Superfluous to say, it is foolhardy for him to believe that he can challenge or stand them. It also goes without saying that he has not acted in the interest of the Gambians by obstinately executing the inmates. The Gambia is not an island. In other words, it cannot live in isolation. We need the help and co-operation of the international community. Besides, his impetuous act can spell doom for him. It can backfire or militate against him contrary to his expectations. <br>" +
                    "<br>" +
                    "Souring of Gambia- Senegal Relations<br>" +
                    "Jammeh’s decision to execute two Senegalese nationals without putting the Senegalese authorities in the picture has the danger of souring the relations of The Gambia and her neighbour the sister Republic of Senegal. Many Senegalese and Gambians received the news with indignation and perplexity. The Senegalese president, His Excellency Macky Sall instructed his prime minister, Abdoul Mbaye to summon the Gambian High Commissioner to Senegal to his office for discussion, threatening that the diplomat would be expelled forthwith if he failed to answer or arrived a minute late. As His Excellency President Macky Sall explicitly and aptly put it, The Gambia is a sovereign nation but has no right to execute Senegalese without passing through the diplomatic channels, as that can impact negatively on the relations of the two countries. I quite agree with him. Jammeh should have had the courtesy to liaise with the Senegalese authorities on the issue before and after the executions, or even hand their nationals to them for trial in their home country for the sake of good relations, peace and harmony. This jogs my memory to the case of a Senegalese who was accused of a crime carrying the death penalty in Saudi Arabia. Despite the strictness of the Saudi authorities in applying the death penalty, they agreed to hand over the man to their Senegalese counterparts for trial in Senegal after negotiations. If the Saudis can behave towards Senegal in such a manner, I wonder why Jammeh who claims to be a pan-Africanist cannot do the same thing.<br>" +
                    "<br>" +
                    "Reactions<br>" +
                    "The international community reacted swiftly by condemning the executions unequivocally and calling on Jammeh not to execute the remaining death row inmates, with some threatening to take drastic measures against him. <br>" +
                    "<br>" +
                    "Gambians in the Diaspora reacted by demonstrating in different cities denouncing Jammeh and distributing petitions, with some tearing his photos into pieces. Some went to the extent of calling for the resignation of Jammeh’s associates. This call is good, for that is expected of a man or a woman of principles in such a situation.  However, I very much doubt whether those concerned will heed to it. Judging by the attitude of Gambians regarding prestige, title, status and position, I will be very much surprised if they resign as a way of safeguarding their integrity or dignity, if at all they have any. As we all know, none of Jammeh’s associates resigned following the massacre of school children in April 2000 and the aforementioned gruesome assassinations. Instead, they stayed on and continued defending his interest and running errands for him to the detriment of the masses till they were given the sack. This nasty habit of defending injustice or serving Jammeh at the expense of general interest to keep one’s job should be kicked out, and the earlier the better. It does more harm than good to us as a nation. We should change attitude for the betterment of all as Allah has said in the Glorious Qur’an: “Allah would not change the situation of a nation (people) unless they change their attitude.”<br>" +
                    "<br>" +
                    "Jammeh’s defenders wasted no time in trying to counter such furious reactions. They started by issuing a poorly-crafted press release through the Ministry of Justice dispelling an unspecified rumour and, at the same time, defending the right of The Gambia to implement its laws as a sovereign nation. That ambiguous press release was interpreted by some people as denying the report of the execution of nine inmates carried by the Freedom Newspaper while some saw it as confirmation of the report. The said press release was followed by another one issued by the Ministry of Interior informing the general public of the execution of nine inmates and justifying the act vis-a-vis the Gambian constitution. Although the second press release told us that the executions were carried out by firing squad on Sunday 26th August 2012 whereas the Freedom Newspaper report said they took place on Friday 24th August 2012 and were carried out by lethal injection, the same names and number of people featured in both the press release and the report. For this reason, many people believe that the Freedom Newspaper report was accurate and that it prompted the Gambian authorities to come out and announce the executions. Hence, they censured Jammeh for being deficient in transparency and economical with the truth. They argued that Jammeh should have been bold or man enough to announce the executions of the inmates immediately rather than trying to keep people in the dark, as he had the nerve to announce his intention to execute them.<br>" +
                    "<br>" +
                    "Later, Jammeh’s associates mobilized people to go the State House to express solidarity with him and appeal to him to refrain from executing the remaining death row inmates as intended. Some government officials seized the opportunity to outdo each other in justifying the executions arguing that they are in line with the dictates of our constitution and that those executed have been tried fairly. They contended that the issue was being politicized or blown out of proportion by malevolent people and that Gambians in the Diaspora were using it to secure papers. Religious leaders and the Supreme Islamic Council added their voices by endorsing the executions and eulogizing Jammeh. <br>" +
                    "<br>" +
                    "The arguments advanced by these spin doctors are refutable. Many people lack confidence in our judiciary by virtue of the undeniable fact that it is manned by judges and magistrates of questionable character and dubitable qualifications who can accept the testimony of a liar, as evidenced by what we saw in the trial of ex-army officers during which a state witness confessed having lied. Jammeh has said publicly in no uncertain terms that the judiciary cannot be independent as it is paid by the state and that he will intervene if it fails to put this into account in its rulings in cases in which the state has interest. Jammeh is fond of threatening to send people to jail as if he dictates the judiciary. Based on Jammeh’s utterances and the fact that the state wins most of its cases, one can rightly draw a conclusion that our judiciary is not independent as Jammeh’s prevaricators want to fool us into believing.  Therefore, there is the possibility that those executed have not been tried fairly. Three of them (the ex-army officers who attacked the military camp in Kartong) did not commit murder, which suggests that their execution was based on treason. It is improper for Jammeh to execute those people on the grounds of treason, for he has committed the same- or a more serious- crime by overthrowing a democratically elected government. Now that he has executed people for committing treason, he and his fellow coup-makers who are still alive should surrender themselves for execution for the sake of justice and fair play which he preaches. According to reports, a mad man was among those executed. This is wrong from both the legal and religious perspectives. Even if he had committed murder, it was not premeditated. Therefore, he should have been taken to a mental home or a psychiatric hospital rather than being killed. Reports also have it that the victims were abused physically, mentally and sexually before being killed, with some of their organs and other body parts removed for ritual purposes. It is also alleged that the bodies were buried in one mass grave or fed to Jammeh’s crocodiles like animal carcasses. Given the fact that the bodies were not given to the families of the victims but disposed of hastily, there might be some elements of truth in these allegations. The onus is now on Jammeh to prove those peddling the allegations wrong by exhuming the bodies and conducting post-mortem or autopsy on them to show the whole world that they are intact. <br>" +
                    "<br>" +
                    "It is ironical for Jammeh’s associates to accuse people of using the issue to secure papers in the West. It is common knowledge that most of them- including Jammeh- have sent their loved ones to settle in the West. It is also an open secret that many of them send their wives to deliver in the West with the sole aim of securing Western citizenship for their kids, and Jammeh is no exception to this. Additionally, it is a well known fact that some of them have spent ages in the West before returning home to serve Jammeh. Who is fooling who? It is an erroneous belief that Diaspora Gambians who criticise Jammeh do it for papers, as many of them have already got papers. Whether they have papers or not, Gambians in the Diaspora are free to criticise Jammeh because they have a stake in the running of their country of origin. I put it to Jammeh’s defenders that it is easier to brand others unpatriotic citizens than to prove oneself as a patriotic citizen. Whatever defence or argument they come up with, the fact remains that the problem is Jammeh’s making. He is entirely reproachable, and trying to shift the blame to others cannot and will not work.<br>" +
                    "<br>" +
                    "Those Jammeh supporters who are appealing to him to stop the executions should have made their pleas before he began- like the members of the international community and human rights organizations did, for prevention is better than cure. It does not tell well of our Islamic religious leaders and the Supreme Islamic Council to express solidarity with Jammeh over the executions or try to justify his act, as they exercised taciturnity and remained indifferent after the massacre of the school children and the indemnification of the perpetrators. As far as I can remember, only one out of the lot had the guts and sincerity to denounce the acts. Although he is labelled as opposition to Jammeh’s regime by Jammeh himself and his supporters, he is hailed as a hero and defender of the truth by most Gambians, my humble self included. When Jammeh ordered a witch-hunting exercise forcing innocent people to drink a poisonous concoction- which caused serious illness and death- neither the religious leaders, nor the Supreme Islamic Council stood against it. As usual, they behaved as if things were normal. However, a brave politician and human rights defender risked his life and challenged Jammeh openly, leading to his arrest. His heroic deed saved the lives of many people who could fall victim of that cruel, inhumane exercise. What is expected of our religious leaders and the Supreme Islamic Council at this crucial moment is to tell Jammeh to return the bodies of those executed to their family members for decent burial in accordance with the teachings of Islam. I hope my former Arabic Grammar student who is an admirer and ardent defender of Jammeh will do him a favour by enlightening him in this regard using his knowledge of Islam. </font>  <br>"
            ,
            "<font color=\"black\"><b>Intolerance: A Catalyst for Catastrophe</b><br>" +
                    "<br>" +
                    "Intolerance can be defined as inability or lack of willingness or readiness to accept ideas, ideologies or ways of behaviour of others or refusal to co-habit, co-operate, interact or deal with people or members of a group one conceives to be different from oneself or different from the members of one’s group. <br>" +
                    "<br>" +
                    "Experience has taught that intolerance engenders conflicts and is most dangerous where it is connected with religious, racial/tribal/ethnic and political sentiments, each of which can influence the others.<br>" +
                    "<br>" +
                    "What obtains in northern Nigeria is a glaring example of religious intolerance. There, Muslims and Christians there are always at daggers drawn, killing each other and vandalizing churches, mosques and other valuable properties. This is not in the interest of either of the contending parties, as both suffer casualties and material losses besides having their daily businesses hampered or interrupted, which would not happen if they co-habited in peace.<br>" +
                    "<br>" +
                    "Religious intolerance can be interpreted as ignorance of the teachings of the Religious Scriptures- particularly the Muslim and Christian ones- or blatant, flagrant disregard of such teachings. Allah the Almighty has stated in the Glorious Qur’an that there is no compulsion in religion. According to the Qur’an, those who call people to God should do it with wisdom and fair exhortation- not with violence. The Holy Bible enjoins us to love our neighbours as we love ourselves. This injunction concurs with the saying of Prophet Muhammad (peace be upon him) that he who believes in Allah and the last day would not harm his neighbour. The venerable prophet (peace be upon him) signed peace pacts with Christians and Jews in Medina and lived with them in perfect peace. Thus, people of different faiths who live together can enjoy veritable, durable peace if they understand and follow the teachings of religion.    <br>" +
                    "<br>" +
                    "The Rwandan genocide involving the Hutu and the Tutsi tribes, in which an estimated number of 800,000 people were massacred in 100 days, serves as a pertinent example of racial/tribal/ethnic intolerance. Added to this appalling holocaust is the displacement of a large number of people who suffered miserably, coupled with a very great loss of properties. The clashes between the Hutus and the Tutsis in neighbouring Burundi and the Hemas and the Lendus in the Democratic Republic of Congo (DRC), former Zaire, also exemplify racial/tribal/ethnic intolerance. <br>" +
                    "<br>" +
                    "Again, it can rightly be stated that having knowledge of the teachings of religion and practising such teachings could help prevent or avoid a tragedy of this nature and magnitude. The Holy Qur’an reads in this regard: “Oh you who believe, We have created you from a single pair of male and female and made you into nations and tribes so that you may know each other. Verily, the most honoured among you is the one who fears God the most. God is Knowledgeable and well Experienced.”  <br>" +
                    "<br>" +
                    "It can be seen from the above citation that no one can rightly claim superiority over others on the basis of race, tribe or ethnicity, and such a claim can be interpreted as challenging God’s wisdom and intelligence. Logically and scientifically speaking, such a claim is preposterous and untenable, for human beings are born equal and made of the same materials, which makes it folly to hate or look down on others based on race, tribe or ethnicity.<br>" +
                    "<br>" +
                    "Examples of political intolerance are plentiful in Africa where politicians on the opposite sides of the political divide are always locked in squabbles, with the members of each side defaming or demonizing the other. Owing to the insincerity, hypocrisy, selfishness and greed characterizing African politics in many cases, political intolerance impacts heavily and negatively on tribalism. In Africa, perfidious, power-hungry and blood-thirsty politicians have the nasty habit of fanning the flames of tribal sentiments for political gains. <br>" +
                    "<br>" +
                    "The Ivorian crisis, which claimed so many lives and displaced a colossal number of people, can be cited as an example in this respect. In Ivory Coast, discriminatory laws were passed with the sole aim of barring popular candidates from contesting in elections as a way of guaranteeing victory to less popular candidates. Chief among these is the heatedly-disputed ivoireté law according to which some Ivorians were deemed more Ivorian (bona fide) than others who were considered to be second-class citizens or foreigners, and hence have less rights than the members of the former category, thereby disenfranchised. This silly act by crooked, errant politicians split the country into two main parts for quite a long time: the northern part dominated by Muslims and controlled by the New Forces rebel group, and the southern one dominated by Christians and controlled by the government. A remarkable fact is that a very large number of the inhabitants of the northern part are from the Dioula tribe whereas the southern part is predominantly inhabited by other tribes.      <br>" +
                    "<br>" +
                    "Likewise, politicians have a big share of the blame in the Rwandan genocide, as evidenced by the conviction of former politicians and the confessions of former Prime Minister Jean Kambanda at the Rwandan war crimes tribunal. The same thing can be said about the crisis in Burundi where Nelson Mandela’s idea of rotating presidency and having in place a president from one of the two tribes and a vice-president from the other tribe was implemented to resolve the problem but without attaining the desired degree of success. The politicians of these two countries can be said to be tarred with the same brush as their counterparts in the DRC where the president, Joseph Kabila was at one time assisted by four vice-presidents chosen from different rebel factions and different tribes/ethnic groups with the view to resolving the crisis which still fails to subside. It is worthy to note here that DRC is a misnomer for Zaire, judging by the behaviour of her politicians.<br>" +
                    "<br>" +
                    "The civil wars in Liberia, Sierra Leone and Guinea Bissau had some elements of tribal/ethnic and political intolerance blended together in that many people fought to help leaders from their tribes/ethnic groups mount or stay in power, which made the situation enormously catastrophic and grave. An astronomical number of people were killed, with many maimed. <br>" +
                    "<br>" +
                    "The war involving Islamic groups in Algeria and the rebellion involving the Lord Resistance Army (LRA) in Uganda can be viewed as springing up from religious and political bigotry. In the former case, the Islamists resorted to venting their spleen on people after the cancellation of the results of elections which were widely believed to be won by them, and were hence confronted by government forces. This created great terror and led to many deaths and destruction of properties. In the latter case, the leader of the LRA, Joseph Cone was engaged in abducting, killing and mutilating people, especially women and children. He claimed to have the intention of overthrowing the Ugandan government and rule his country by the Ten Commandments of the Holy Bible, but his acts run counter to the teachings of this holy book. Superfluous to say, the resulting confrontations between the LRA and government forces also proved to be calamitous.   <br>" +
                    "<br>" +
                    "The conflict between the Palestinians and the Israelis can be analyzed as having religious, racial and political dimensions, and being influenced by both internal and external factors, thereby making it extremely complex and difficult to resolve. Arabs, Muslims and Jews in and outside Palestine and Israel, irrespective of whether they are politicians or not, may be held responsible for this long-lasting, bloody conflict.  Everything boils down to intolerance, as support for and opposition to either side of the conflict is normally based on religious, racial and political reasons or sentiments.<br>" +
                    "<br>" +
                    "Our homeland- The Gambia is plagued by a stupendous, alarmingly-high degree of political intolerance, as exemplified by the persecution and liquidation of politicians, journalists and religious leaders with dissenting voices. Those opposed to the views of the leader are termed as traitors and thus victimized or brutalized whimsically and capriciously. This has created perpetual fear, resentment and discontentment. It is disheartening that this objectionable, repugnant behavior of our authorities is not only condoned but also endorsed, encouraged and justified by many people who claim to be virtuous, decorous, peace-loving, pious and patriotic. Equally deplorable is the fact that those who voice their concern or endeavour to change the situation for the better are regarded as detractors, saboteurs or troublemakers. It is a pity that this volatile situation has continued unabated for too long. I pray and hope that it will not snowball or aggravate.<br>" +
                    "<br>" +
                    "We should bear in mind that no country or region on earth is immune to conflicts and their undesirable, unsavory accompaniments in the absence of tolerance. Ivory Coast, which used to be a safe haven and attracted a huge number of migrants during the time of the late President Felix Houphet Boigny, is a clear testimony to this. What has befallen Ivory Coast can happen in any country where people change attitude from ‘tolerance’ to ‘intolerance’ as the Ivorians did. This statement is substantiated by the Qur’anic verse: “God would not change the situation of a people unless they change their attitude”. In other words, God changes the situation of a nation only when they change their attitude or behaviour. So, the citizens of a country can expect positive changes in their lives if they change attitude from bad to good. By the same token, they should not be surprised when they see negative changes in their lives if they change their behaviour from good to bad. <br>" +
                    "<br>" +
                    "Intolerance breeds discord which can germinate into conflicts that yield affliction or sufferings, affecting everybody, directly or indirectly. Therefore, it is wise for those countries renowned for tolerance to try to safeguard or maintain such a virtue if they want to avoid conflicts and live in peace and harmony, for prevention is better than cure. Countries that are marked by intolerance and conflicts should try to change attitude for the better if they want to manoeuvre their way out of their awkward situation or troubles. To enjoy global peace and stability, people all over the world should learn to exercise tolerance and restraint. </font>   <br>" +
                    "<br>"
            ,
            "<font color=\"black\"><b>Imam or Image-maker?</b><br>" +
                    "<br>" +
                    "Imam or Image-maker?<br>" +
                    "I am fully convinced that you are well versed in Islamic Studies,<br>" +
                    "But I very much doubt your sincerity as an Islamic scholar<br>" +
                    "People ask whether you are really an Imam or an Image-maker,<br>" +
                    "Based on your recent sermon which many of them see as propaganda<br>" +
                    "You have apparently swerved to the wrong path,<br>" +
                    "And hence the need to draw your attention<br>" +
                    "Khalipha Umar Ibn Khatab (may Allah be pleased with him) once said that a leader and a learned person who are not righteous are a menace to society<br>" +
                    "This saying befits you and your master<br>" +
                    "A crooked leader is dangerous in that he abuses his power,<br>" +
                    "As your master does on daily basis  <br>" +
                    "The danger with an unrighteous learned person is that he deliberately distorts facts, <br>" +
                    "And can easily influence and mislead people using his knowledge,<br>" +
                    "As evidenced by the cheers you received from the congregation while delivering the aforementioned sermon<br>" +
                    "But the latter is more dangerous and worse than the former,<br>" +
                    "Because his impact is long-lasting  <br>" +
                    "The former is less dangerous to society,<br>" +
                    "Because he endangers his own life through his misguided acts,<br>" +
                    "As your master is doing daily, <br>" +
                    "And ends up perishing or dying miserably,<br>" +
                    "As is the case with most dictators<br>" +
                    "<br>" +
                    "Imam or Image-maker?<br>" +
                    "You expressed your disapproval over a question related to the assassination of a journalist asked by his colleagues,<br>" +
                    "Saying that those who ask the question should also ask questions about crimes committed by others <br>" +
                    "Thinking that your argument would prove your master innocent<br>" +
                    "You have clearly shown your lack of mercy through your utterances<br>" +
                    "What is expected of you is to pray for the soul of the victim to rest in perfect peace,<br>" +
                    " And call for justice in that wicked crime<br>" +
                    "I put it to you that your argument is weak,<br>" +
                    " Both from the Islamic and constitutional points of view,<br>" +
                    "And thus beg to differ with you<br>" +
                    "According to our prophet (may peace be upon him), everybody is a shepherd responsible for what is entrusted to him- KULUKUM RA-IN WA KULUKUM MAS-ULUN AN RA-YATIHEE,<br>" +
                    "And that an Imam is a shepherd at the mosque, and a landlord a shepherd in the house<br>" +
                    "It therefore goes without saying that Islam regards the leader of a country as a shepherd responsible for the security and welfare of his people<br>" +
                    "Your master has sworn by the Holy Qur’an to serve his people without fear or favour, affection or ill-will as enshrined in our constitution <br>" +
                    "Thus, his reluctance or refusal to track down and punish the perpetrators of the crime can be interpreted as “ill-will” and “fear”,<br>" +
                    "Violation of oath,<br>" +
                    "And total disrespect for the Holy Qur’an and the constitution<br>" +
                    "You cannot prove your master innocent by reminding us that other people have committed crimes,<br>" +
                    "And the fact that other people have committed crimes does not give your master the licence to commit or condone crimes as you implied<br>" +
                    "A crime is a crime irrespective of who has committed it,<br>" +
                    "But it is worse when committed or endorsed by someone who is expected to combat or prevent it like your master<br>" +
                    "Those who try to know the killers of the journalist or dig out information on the issue are well justified<br>" +
                    "It is proper for the members of a profession to sympathize with each other,<br>" +
                    "And fight for the rights of offended or victimized colleagues<br>" +
                    "<br>" +
                    "Imam or Image-maker?<br>" +
                    "You insinuated that journalists who criticize your master are sponsored by the West,<br>" +
                    "And that they refrain from criticizing the West in order not to lose money<br>" +
                    "My response to you in this regard is that not everybody is materially-minded,<br>" +
                    "Like you who blatantly defend injustice for material gain,<br>" +
                    "And your master who is engaged in chequebook diplomacy to line his pockets,<br>" +
                    "Befriending countries that dish out money without conditions attached,<br>" +
                    "Unlike the US and the members of the EU that demand respect for democracy and human rights, <br>" +
                    "Which your master finds extremely difficult to meet<br>" +
                    "Journalism is not a lucrative or plum job <br>" +
                    "It involves more sacrifices than material gains<br>" +
                    "It is very risky due to the intolerance of leaders like your master<br>" +
                    "<br>" +
                    "Imam or Image-maker?<br>" +
                    "You praised your master highly for changing the work schedule of the public sector making Friday day off using Islam as justification,<br>" +
                    "Citing the Qur’anic verse that urges people to close business and hurry up to the mosque in remembrance of Allah when the call is made for prayer on Friday, <br>" +
                    "As a way of defending the unpopular declaration of your master<br>" +
                    "Your master’s decision was a rash, unilateral one,<br>" +
                    "For which reason he had to make amendments twice exempting some government institutions and departments<br>" +
                    "Your master’s behaviour contradicts the Glorious Qur’an which encourages consultation,<br>" +
                    "As in the verses “Consult them in the matter”- SHAAWIRHUM FIL ALRI,<br>" +
                    "And “They (the Muslims during the time of the venerable prophet) conducted their affairs based on consultation- INA AMRAHUM ASHAWRAA<br>" +
                    "The verse you quoted to back your master’s decision does not say that Friday is a rest day in Islam,<br>" +
                    "As it has mentioned the closure of business when the time is up for Friday prayer,<br>" +
                    "Indicating that people are allowed to conduct business as usual before and after Friday prayer<br>" +
                    "Islam recommends that we strike a balance between work and worship, As substantiated by the saying “Work hard for your benefit in this world as though you will live \tfor ever, and work hard in preparation for your life in the next world as if you are going to die tomorrow”- IMAL LIDUNYAAKA KA-ANAKA TA-ESHU ABADAN, WA IMAL LI AAKHIRATIKA KA ANAKA TAMUUTU GHADAN<br>" +
                    "Evidently, it is improper, imprudent and irresponsible for your master to make such a decision under the guise of Islam<br>" +
                    "His act is hypocritical<br>" +
                    "He would not persecute Imams if he was genuinely interested in the practice of the teachings of Islam as he wants to make us believe<br>" +
                    "<br>" +
                    "Imam or Image-maker?<br>" +
                    "You called on people to treat your master with respect,<br>" +
                    "Lamenting that they insult him,<br>" +
                    "Cautioning them to desist from insulting him,<br>" +
                    "Saying that those who insult their leaders are bound for hell fire <br>" +
                    "Respect is reciprocated but not earned merely by virtue of position or status, <br>" +
                    "Nor can it be forced as your master believes,<br>" +
                    "Therefore, your master should respect people if he expects them to treat him with respect<br>" +
                    "I do not approve of insulting,<br>" +
                    "But I understand that those who insult your master do it in reaction to his derogatory remarks, foul language and other forms of oppression<br>" +
                    "Your master can save himself from insults by addressing people in a polite, diplomatic manner,<br>" +
                    "As our prophet urged us in his saying “A nice word is charity”- KALIMATUN TAYIBATUN SADAQATUN,<br>" +
                    "Treating them with justice,<br>" +
                    "And avoiding oppression in all its shapes and forms<br>" +
                    "People who insult your master may meet him in hell fire if they go there,<br>" +
                    "As he is undeniably an oppressor,<br>" +
                    "And Allah has said plainly in the Holy Qur’an that a very severe punishment awaits oppressors- ASDHAALIMUUNA A-ADA LAAHU LAHUM ATHAABAN ALEEMAN<br>" +
                    "<br>" +
                    "Imam or Image-maker?<br>" +
                    "You thanked your master and prayed to Allah to bless him<br>" +
                    "I thank Allah and pray to Him to guide you and your master<br>" +
                    "I also pray to Allah to bless our country as a whole and shower His mercy on the victims of your master in particular<br>" +
                    "Stop glorifying and mystifying your master,<br>" +
                    " And always remember the Islamic saying that the best Jihad (fight in the cause of Allah) is to tell the truth in front of a tyrant<br>" +
                    "Bear in mind that your master has imposed himself on his people by staging a coup d’état to mount power,<br>" +
                    "And that we have been told in Islam that Allah curses a person leading people who do not like him  <br>" +
                    "On a final note, I exhort you to abide by the Islamic principle that we should not be loyal to a creature (human being) to the extent of being disloyal to the Creator (Allah)- LAA TAA-ATA LIL MUKHLUUQI FI MA-ASIATIL KHAALIQI </font><br>" +
                    "<br>"
            ,
            "<font color=\"black\"><b>Position of Responsibility: Who Is Unqualified?</b><br>" +
                    "<br>" +
                    "Our venerable prophet, Muhammad (may peace be upon him) is reported to have said that one who expresses a desire to hold a position of responsibility should not be given the mandate, and that he once declined the request of one of his disciples to be appointed governor of one of the regions of the then Islamic State, saying that his request rendered him unqualified for the post. Superficially, this Islamic principle runs counter to the principles of democracy which generally require those who feel qualified to occupy positions of responsibility to seek the mandate of the people or those in high authority. The questions arise now: What is the logic behind this Islamic principle? How can we interpret it or reconcile it with democratic principles? Should we jettison or discard the latter for the former?  <br>" +
                    "<br>" +
                    "The above questions can be answered thus. During the time of Prophet Muhammad (may peace be upon him) and sometime after he passed away, people were nominated or appointed to positions of responsibility without expression of desire. Therefore, deviating from the norm by seeking appointment would arouse suspicion or make people believe that the individual concerned wanted to serve his personal interest rather than serving the interest of the people. Even in democratic societies, certain positions are filled by way of nomination, and seeking appointment to them would generate negative interpretation, rightly or wrongly. Those over-ambitious to hold positions of responsibility tend to be egoistic or selfish. The rationale behind the Islamic principle is simply to ensure justice, fair play and peace by preventing self-centred or self-serving people from being elevated to positions of responsibility, which is in accord with genuine democracy. I accentuate the word genuine because not any act qualified as democratic or undemocratic is really so. It therefore follows that not all self-proclaimed democrats can be accepted as such, and not all those branded as undemocratic are truly so. To many, anything that favours them and puts their opponents at a disadvantage is democratic, whereas anything that does not is undemocratic. To others, what they practise or what pleases them is democratic, and what the enemy does is undemocratic. Put in crude terms, the meaning of the word democracy is intentionally distorted for various reasons, the main one being egocentricity or selfishness. Words like dictatorship, patriotism, terrorism and jihad fall victim as well. This explains the motive behind the coining of the term dictator for development by a head of state, in response to his   critics who view him as a dictator due to his sheer lack of democratic tendencies. He baptized himself Dictator for Development in an attempt to justify his dictatorial attitude. Hence, we cannot separate the chaff from the wheat by merely listening to or reading a political discourse. Nevertheless, democracy could be of immense benefit if not misconstrued as pointed out above. Therefore, I do not call for its abandonment. I rather advocate it. <br>" +
                    "<br>" +
                    "However, the political situation in Africa depicts fake democracy in many cases. In Africa, the norm is to seek power or endeavour to remain in power through violent, knavish, fraudulent or deceitful means while trying to fool people into believing that one is sincere, patriotic, impeccable, infallible, indispensable or invincible. This clearly explains why our venerable prophet (may peace be upon him) cautioned against appointing over-zealous aspirants to positions of responsibility.          <br>" +
                    "<br>" +
                    "Some African countries espouse unique-party system of government otherwise known one-party state, and some that claim to be democratic or multi-party states are characterized by one-man rule, coupled with zero tolerance to dissent and freedom of expression. Hence, it is not surprising to hear an African head of state say in plain language that he would not compromise with his perceived enemies or take things for granted as he had put his life on the line to come to power. My question to that head of state is: Have you sacrificed or risked your life more than Nelson Mandela- my hero- who languished in jail for twenty-seven odd years and retired honourably from active politics after serving as president for only four years? Some African leaders reject the idea of having a presidential term-limit enshrined in their constitutions, while some accept that, only to amend the constitution later- with the complicity of rubber stamp parliaments- to stay in power as life-presidents. Some African politicians dish out prodigious sums of money to bait the electorate or make specious promises to them during campaigns but desert them or inflict sufferings on them after assuming office. Others resort to harassment, vilification, castigation, insulting or issuing threats.   <br>" +
                    "<br>" +
                    "To cling onto power, some African leaders rule with iron hands by dismissing, torturing, incarcerating or executing their opponents or perceived enemies as a way of intimidating the populace, while others practise nepotism blatantly, hire the services of praise-singers or use religion as a means of hoodwinking people. In some African states, the constitution is subjected to endless amendments to arm the president with sweeping powers, or blatantly violated where it conflicts with his selfish interest. In those countries, the members and supporters of the ruling party are treated as first-class citizens by being granted special favours. Besides, they are licensed to behave anyhow without any penalty. They can act in total contravention of the law or take the law into their own hands and easily get away with it or go scot-free, while the rest of the population are branded as detractors or unpatriotic citizens, and hence victimized or punished harshly for flimsy reasons or minor offences.  <br>" +
                    "<br>" +
                    "Thus, many people in those countries identify with the ruling party by serving as sycophants, puppets and torture tools, always trying to justify the unjustifiable and defend the indefensible, portraying their leaders as demigods while demonizing their opponents and brutalizing innocent citizens. Imagine a person whose relative has disappeared under mysterious circumstances during the reign of a brutal dictator going public to defend the ruthless despot, trying to brush his sadistic, repugnant,  reprehensible deeds under the carpet, claiming to be hundred percent loyal to him, labelling his critics as cowards and unpatriotic citizens! This is the climax of insincerity, hypocrisy and cowardice, to say the least! What does such an errant, misguided, mendacious, devious and heartless character expect to gain from his abhorrent, outrageous, obnoxious acts? What is expected of him is to simply keep quiet if he lacks the nerve to protest over the lugubrious, melancholic disappearance of his loved one. Some people serve as professional sycophants under different regimes in those countries, claiming to have switched allegiance or loyalty, eulogizing or flattering the head of state while denigrating or lambasting his predecessor whom they used to praise to the extent of equating or associating him with God. It is very common to see unscrupulous politicians behaving as poacher turned gamekeeper in those countries. Such greedy, selfish and opportunistic sorts would launch blistering criticism against their governments while in the opposition, only to join them later and become their fervent defenders and bitter enemies of the opposition and the press. It is also common to see ousted politicians going round preaching democracy, suggesting constitutional amendments, policies and laws that they never contemplated championing while in office. Some electoral officers dance to the tune of the ruling party, turning deaf ears and blind eyes to the concerns and complaints of the opposition in those countries. Opposition parties are denied their constitutionally-allocated airspace in the public media which is monopolized by the governing party. To add insult to injury, members of the opposition and their supporters are constantly denied their constitutional rights to assembly and subjected to all sorts of victimization or brutalization by security forces and law enforcement agents who are supposed to remain neutral, protect all citizens and enforce the law without fear or favour, affection or ill-will.   <br>" +
                    "<br>" +
                    "It is common knowledge that some African leaders and their associates become superfluously rich overnight or in the twinkling of an eye and spend thriftlessly, consoling the suffering masses by telling them that the hardship they experience springs out from inevitable or uncontrollable factors; that it is the reality of the world we live in; that they are not alone in their sufferings and that they are even well-off compared to their neighbours. Some African leaders who claim to be Pan-Africans and cultivate the habit of slandering Westerners plunder and spend astronomical sums of money to secure Western citizenship for their children by sending their wives to deliver in the West, particularly the USA. They also use their loot or rapidly-accumulated wealth to purchase expensive mansions and open bank accounts for their families in the West. They do this to ensure the security and safety of their families, thinking that they are smart. This is grossly hypocritical, ironical, irrational and unfair! It shows clearly that those crooked leaders are fully cognizant of the fact that they are not treating their people nicely as expected of them. They know that they oppress their people too much- hence their fear for the security and safety of their families in their countries. My message to them is that the best way to guarantee the security and safety of their families is to treat their compatriots with justice and mercy. If they fail to see reason and kick out their nasty behaviour or desist from oppressing people before it is too late, they may find it extremely hard or impossible to succeed in providing protection or security for their families as desired, no matter what tactics they use to achieve their aims. It is foolhardy for them to deny people their god-given, constitutionally-guaranteed rights and expect their families to enjoy such rights. As a man sows shall he reap! If they were fair with their people, they would create a peaceful, safe environment in their countries- like that in the West, which they want their families to enjoy. This is more reasonable and advisable than seeking peace and security for their families at the expense of their compatriots whose inalienable rights they mercilessly, shamelessly and senselessly seize for their selfish interest. What is good for the goose is good for the gander.                            <br>" +
                    "<br>" +
                    "How can we expect transparency, accountability and probity in such a situation? In fact, these terms have long ago been expunged from the vocabulary list of the political leaders who initially claimed to be using them as guiding-principles chanting them raucously and monotonously at every opportune moment. The reason for the sudden disappearance of this once famous triplet into thin air is that those fake, self-proclaimed patriots, like everybody else, know fully well that they have conspicuously violated the very rules they had laid down. How can we expect those involved in such a dirty game to serve the interest of the people? Such selfish, power-hungry and bloodthirsty people are not qualified to run even a household, let alone govern a nation. Evidently, one is amply justified in saying that seeking power or appointment to a position of responsibility in Africa is synonymous with seeking self-aggrandizement and self-enrichment in many cases.   <br>" +
                    "<br>" +
                    "If you have ever wondered why the press is muzzled in most parts of Africa, here is an answer. If you want to know why election results are furiously disputed or why coups are common in Africa, here is an explanation. In Africa, many people want to rule at all cost, not only to rule but to rule forever for selfish gains. This explains why Africa is politically unstable and why regime change is always bitter for some people in Africa. <br>" +
                    "<br>" +
                    "Although altruism- a virtue found in Nelson Mandela- is alien in most African politicians, our political leaders should- at least- try to put national interest before personal or individual interest. A person who puts his/her interest before national interest is unqualified for position of responsibility. We can thus draw a conclusion that a leader who has mounted power through the barrel of the gun and vowed to overstay his welcome or perpetuate himself at all cost is unqualified to be head of state. The same thing applies to a leader who has abundantly demonstrated his reluctance to relinquish power peacefully by saying plainly and publicly that he cannot be removed by any means (neither election nor coup) and that he can slaughter ten thousand of his compatriots and have sound sleep. His utterance is utterly provocative, spiteful, malicious, irresponsible, infantile and immature. It can rightly be interpreted as inciting violence. Such a leader is manifestly selfish and cannot truly claim to be peace-loving, development-oriented or have the interest of his country and people at heart. He is totally unqualified! </font><br>" +
                    "  <br>"
    };
}
